### ISSUE TITLE
No matching export for import "OggVorbisEncoder"

### ISSUE THREAD

**Issue by WickyPlays** [spessasus/SpessaSynth#28]
So... This happened when I was upgrading SpessaSynth from 3.9.21 to the latest version for a Tauri + Vite project. Version 3.9.21 doesn't have this problem though:

+ Already did a reinstall as well, doesn't work either.

I'm assuming this probably is because the ES6 import format doesn't play nice inside .js file like this.

![Code_RWbdxdLK3u](https://github.com/user-attachments/assets/71872113-d1ee-445c-b137-459f2ed35819)

**Comment by spessasus** [comment]
I have fixed it (the function to export was encodeVorbis, not OggVorbisEncoder), but I encountered another issue.

You see, the OggVorbisEncoder is  a *really*, *really* large file. (around 1.1MB) That's why when saving the soundfont you're required to import it yourself to ensure that it isn't loaded unless absolutely necessary.

But the index.js file has to contain all exports available, so the encodeVorbis (which imports OVE) has to be included too. This results in webpack always bundling the encoder, even though I've only imported the synthetizer. This results i a 2MB js file which is completely unnecessary.

Do you have any ideas on fixing this or is it webpack's fault?

**Comment by WickyPlays** [comment]
Maybe performing tree shaking would work?

**Comment by spessasus** [comment]
> Maybe performing tree shaking would work?

Could you try it with vite in your project and see if OVE gets bundled?

**Comment by spessasus** [comment]
Yep, tree shaking works fine. I'll add it to the wiki. Thanks!

**Comment by WickyPlays** [comment]
This one works now though.

> > Maybe performing tree shaking would work?
> 
> Could you try it with vite in your project and see if OVE gets bundled?

Yes this one works now.
