### ISSUE TITLE
[BUG] Performance issues after switching soundfonts multiple times by passing new instances of Synthetizer

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [spessasus/SpessaSynth#74]
### Version
*The app or `spessasynth_lib`? Local Edition or `github.io` page? Downloaded from releases or via `git clone`? Please specify.*
`spessasynth_lib` used as a package, `npm` style (in my case `bun`)

### Description
*Provide a clear and concise description of what the bug is.*
I have a keyboard app that I added spessasynth to for playing sf2s. Instead of having a huge .sf2 file I split each instrument into a separate soundfont so the user doesn't have to wait for a huge sf2 file (and I don't have to host it).

Since they are different soundfont files I don't change the patch, instead I load a new instance of `Synthetizer`. I'm not sure if there's any manual cleanup step required, I'm basically running

```ts
channel = new Synthetizer(context.destination, soundFontArrayBuffer); // create the synthetizer
```

each time I change sf2 which reassigns the new Synthetizer instance to the variable.

### Reproduction steps
*Describe the steps to reproduce the behavior.*
I don't have a small repro right now, here's what I'm testing with: https://keyboard.henrikvilhelmberglund.com/instruments/soundfont

1. Click and drag along the notes to play them, sounds fine
2. Switch instruments using the slider a few times (instrument names are wrong but shouldn't matter here)
3. Click and drag along the notes to play them

### Expected behavior
*Provide a clear and concise description of what you expected to happen.*
Expected: Sounds fine
Actual: Audio drops out/glitches/crackles 

### Screenshots
*If applicable, add screenshots to help explain your problem.*

### MIDI files and SoundFonts
*If the issue only persists with specific MIDIs or SoundFonts, add them here too. (preferably .zip)*

### Environment
*If the issue only persists on a smartphone, or only on a PC, or only on Chrome, etc. please specify.*
Happens in both Chromium based browsers and Firefox, although Firefox seems a lot more stable and crackling isn't as bad. I tested only in desktop.

### Additional context
*Add any other context about the problem here that may be helpful.*

**Comment by spessasus** [comment]
Please avoid using multiple synthesizer instances. It is not recommended.

**Comment by spessasus** [comment]
Consider using the [soundfont manager](https://github.com/spessasus/SpessaSynth/wiki/Synthetizer-Class#the-soundfont-manager) for this task.

**Comment by spessasus** [comment]
Here's a longer explanation:

As you probably know, Web Audio runs on *Audio Nodes*. These nodes can be connected and disconnected to each other with the final node being the `context.destination` which are  the speakers.

When you initialize the Synthetizer class, it connects 3 nodes to the `targetNode`:
- `ConvolverNode` - reverb processor. Native for the browser, but very expensive.
- A lot of `DelayNode`s - the chorus. This one is not really important as it's quite cheap.
- `AudioWorkletNode` - this is the main synthesizer, the heart of spessasynth. It generates all the sound and as you might guess, it's the most expensive out of all of them.

I'm assuming that you don't do anything special when you discard the synthesizer. Since you do, all the nodes stay connected.

So even when there's silence, there are a lot of things happening:
- Reverb gets processed
- Chorus gets processed
- Worklet runs through the entire voice chain (it's empty so it quits quickly)

This all happens quite fast, but when you keep making more and more synthesizers without disconnecting the old ones, this stacks up fast. 

So that's why you should consider using only one synthesizer. It's meant for playing multiple various instruments at the same time, and it will perform way, way better than using multiple synths.

`SoundFontManager` was made exactly for your purpose. You can load up your smaller sf2, then use `addNewSoundfont()` when needed. It will combine these two, like you had one soundfont with two instruments. Then, if the user wants to go back to the already loaded instrument, you can just execute a `programChange()` to that patch.

I hope this clears things up.

**Comment by spessasus** [comment]
BTW, I have added this warning to the docs; thanks for reminding me to do that!

**Comment by spessasus** [comment]
The synthesizer can now be destroyed, starting with version 3.22.12. (Remember to update worklet_processor.min.js!)

Though, for your usecase, using [connectIndividualOutputs](https://github.com/spessasus/SpessaSynth/wiki/Synthetizer-Class#connectindividualoutputs) would also work. This is how the web app displays individual channel waveforms.
