### ISSUE TITLE
[QUESTION] Need some clarification on how to get meta event from seq.getMIDI();

### ISSUE THREAD

**Issue by Citrusy0** [spessasus/SpessaSynth#83]
### Documentation Confirmation
*Please confirm that you have read the [documentation](https://github.com/spessasus/SpessaSynth/wiki) and have not found an answer to your question there.*

**Yes**

### Question's Topic
Need some clarification on how to get meta event from `sequence.getMIDI();`

### The Question
I have this piece of code here:
```js
  try {
      const midiFile = await file.arrayBuffer();
      const synth = new Synthetizer(audioContext.destination, soundFontBuffer);
      const seq = new Sequencer([{ binary: midiFile }], synth);
      seq.loop = false;

      const midi = await seq.getMIDI();

      let events = midi.tracks.flat();
      events.sort((e1, e2) => e1.ticks - e2.ticks);

      let newEvents = [];

      //Clarification needed
      for (let i = 0; i < events.length; i++) {
        if (events[i].messageStatusByte >> 4 == 2) {
          newEvents.push(events[i]);
        }
      }

      seq.play();
    } catch (error) {
      console.error("Error handling MIDI file:", error);
    }
```
The goal is I want to get lyrics in which I also want to get starting point where a piece of lyric will begin at which duration; however I need messageStatusByte from `getMIDI().tracks` to be 0xFF to grab meta messages, but since that isn't supported, I did look at the doc to find out that I need to grab from second status byte but... I was confused which second status byte it referred to? `events[i].messageStatusByte == 2`, `events[i].messageStatusByte << 4 == 0x02` or `events[1]`? 

Just for extra, can you have this feature in the default midi.lyrics (if possible that is)?

**Comment by spessasus** [comment]
Hi,

[Here](https://www.recordingblogs.com/wiki/midi-meta-messages) you can read about meta messages. As you can see the first byte of a meta message is `0xFF` while the second byte actually indicates what type of meta message it is (see the table). Since these types don't overlap with MIDI and SysEx messages, spessasynth stores both in the `messageStatusByte`

Here you can see how the MIDI writing code determines whether the message is MIDI, SysEx or meta. You can use that to append `0xFF` if necessary:
https://github.com/spessasus/SpessaSynth/blob/23d4bd96c04ac6f5e95d0d45052a7059107e7afe/src/spessasynth_lib/midi_parser/midi_writer.js#L29-L55

As for `lyrics`, it's an array of the `messageData` property from all `0x05` (lyrics) meta events, in order, created during load time. Since it only includes the `0x05` event data's, there's no need to describe the type of them.
Essentially, the code for creating lyrics is:
```js
const lyrics = [];
midi.tracks.forEach(track => track.forEach(message => {
    if(message.messageStatusByte === 0x05) {
        lyrics.push(message.messageData);
    }
}));
```

I hope this helps.

**Comment by Citrusy0** [comment]
Oh, it was that easy lol. I already know the lyric meta is 0x05 but I was confused the wording in the doc at first. Thanks though.
